name: Test run Discord BOT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot.py
        env:
          token: ${{ secrets.TOKEN }}
          github: ${{ github.repository }}
        run: |
          python bot.py
